---
".gitlab-ci.yml":
  delete: true
".travis.yml":
  global_env:
    - HONEYCOMB_WRITEKEY="7f3c63a70eecc61d635917de46bea4e6",HONEYCOMB_DATASET="litmus tests"
  deploy_to_forge:
    enabled: false
  branches:
  - release
  use_litmus: true
  litmus:
    provision_list:
      - travis_deb
      - travis_ub
      - travis_el7
      - travis_el8
      - ---travis_el
  simplecov: true
  notifications:
    slack:
      secure: >-
        bkgukmfDEw0pA7mx0e8UU4p4GmpWL/s7kC5D/3XyqNilYI5SArkAt5MTnwMn7/GSF0JRspcrt3J9Y69lNseE5dDegArlht6D2c5Ad8o0ibrCN7yuz6XVyiODyYf32+w/lzsaTQJ1E/55HgTKJ9Tzk8sPlLsYcSEt2OGm+hR/2AoaLi6M8WSc5fCmTUI7AgLnT95jbDu5ioJkOILGCet47A24MXKR2jNaQ7KYhiQ8xqXPZ3Zp0N/bZuYjDiYEeRbjHWvALyInQVqCytv9aLW5v7tg4IjhkyYrDf4g5XamU2909uyTgHT+M/nuPsScnyEu5YdSWT9RqoAHhADz+7daFcgVtUIN5K8EEaNmA8b/nXrGnSh2S1MJ/D/lbo176oHiKh/KME0/L7+YfCxnyGMaraUcxVjj9FQzBDRDIiyDqJOVe4v0cpkdEuCgJTgaIJ2NLHVmJzgGYTuIp/xV2/zWEgqNxz977ydsPObU0T0MCqpzaFR7a5zj3hsNlGa25bbehDGUyi7MFi6TVQMRYhldiZXydERCFaBbKfOT5xfNNpu3FZmi7t1Tu2sClZFwKW9OachoDI/NFam6+D/Q2nuuAl+p/L5edeF3ciGTjMr9OGZeLqFS/6fUxfM/GP/3bDBzF8RN6gZW5HQdtJkXq5GbpifKsA9gEL4VbPKqNhEtDss=
appveyor.yml:
  environment:
    HONEYCOMB_WRITEKEY: 7f3c63a70eecc61d635917de46bea4e6
    HONEYCOMB_DATASET: litmus tests
  use_litmus: true
  spec_type: spec
  matrix_extras:
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
  - RUBY_VERSION: 25-x64
    ACCEPTANCE: 'yes'
    TARGET_HOST: localhost
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  simplecov: true
Gemfile:
  optional:
    ":development":
    - gem: github_changelog_generator
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitpod.Dockerfile:
  unmanaged: false
.gitpod.yml:
  unmanaged: false
.github/workflows/nightly.yml:
  unmanaged: false
.github/workflows/pr_test.yml:
  unmanaged: false
.github/workflows/auto_release.yml:
  unmanaged: false
